# store in /etc/ansible of the controller
- name: Transfer and execute a script.
  vars:
    user: osboxes # will differ
  hosts: nodes
  sudo: yes
  tasks:
    - name: Copy and execute kubernetes setup script for each node
      script: /home/{{ user }}/documents/kubernetes-ubuntu-setup.sh
  # feel free to add/remove nodes